### ISSUE TITLE
OSS Hack Weekend: cocuh: qtile: python: 作業ログ

### ISSUE THREAD

**Issue by cocuh** [clear-code/sezemi-2015#31]
https://github.com/qtile/qtile

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by cocuh** [comment]
qtileをxephyerで動かす
for debug

**Comment by cocuh** [comment]
xepherが無限ループする^cにて

**Comment by cocuh** [comment]
http://qtile.readthedocs.org/en/latest/manual/hacking.html

**Comment by cocuh** [comment]
http://www.freedesktop.org/wiki/Software/Xephyr/

**Comment by cocuh** [comment]
ctrl+shiftでgrab or release

**Comment by cocuh** [comment]
xephyrがなんか無限ループしたりcore dumpするのでrecompileする

**Comment by cocuh** [comment]
#TODO crashした時のerror messageがわかりにくい問題

**Comment by cocuh** [comment]
xephyrさんの正規終了方法がわからん

**Comment by cocuh** [comment]
たぶん、このscriptを読み解く必要あり
https://github.com/qtile/qtile/blob/develop/scripts/xephyr

**Comment by cocuh** [comment]
``` python
Xephyr +extension RANDR -screen ${SCREEN_SIZE} ${XDISPLAY} -ac &
```

-acはaccess control disable

**Comment by cocuh** [comment]
extension RANDR ？

**Comment by cocuh** [comment]
あっ察し
https://awesome.naquadah.org/wiki/Using_Xephyr

```

  stop)
    echo -n "Stopping Nested Awesome... "
    if [ -z $(xephyr_pid) ]; then
      echo "Not running: not stopped :)"
      exit 0
    else
      kill $(xephyr_pid)
      echo "Done."
    fi
    ;;
```

**Comment by cocuh** [comment]
#next killする必要があるので、scriptを自分用に書き換える

**Comment by cocuh** [comment]
こちらの実行スクリプトを参考にするとよいかも https://awesome.naquadah.org/wiki/Using_Xephyr

```
 Xephyr -ac -br -noreset -screen 1024x768 :1.0 &
 ZEPHYR_PID=$!
 sleep 1
 DISPLAY=:1.0 awesome -c rc.lua
 kill $ZEPHYR_PID
```

**Comment by cocuh** [comment]
git pull upstream develpしたらこわれた

**Comment by cocuh** [comment]
```
ceback (most recent call last):
  File "/home/cocu/workspace/qtile/scripts/../bin/qtile", line 130, in <module>
    q = make_qtile()
  File "/home/cocu/workspace/qtile/scripts/../bin/qtile", line 107, in make_qtile
    c = confreader.File(options.configfile, is_restart=options.no_spawn)
  File "/home/cocu/workspace/qtile/bin/libqtile/confreader.py", line 46, in __init__
    from .resources import default_config
  File "/home/cocu/workspace/qtile/bin/libqtile/resources/default_config.py", line 27, in <module>
    from libqtile.config import Key, Screen, Group, Drag, Click
  File "/home/cocu/workspace/qtile/bin/libqtile/config.py", line 29, in <module>
    from . import hook
  File "/home/cocu/workspace/qtile/bin/libqtile/hook.py", line 33, in <module>
    from . import utils
  File "/home/cocu/workspace/qtile/bin/libqtile/utils.py", line 27, in <module>
    from . import xcbq
  File "/home/cocu/workspace/qtile/bin/libqtile/xcbq.py", line 50, in <module>
    from .xcursors import Cursors
  File "/home/cocu/workspace/qtile/bin/libqtile/xcursors.py", line 7, in <module>
    from .ffi_build import xcursors_ffi as ffi
  File "/home/cocu/workspace/qtile/bin/libqtile/ffi_build.py", line 25, in <module>
    from xcffib.ffi_build import ffi as xcffib_ffi
ImportError: No module named 'xcffib.ffi_build'
```

こんなエラー

might be difference between system version and local version

**Comment by cocuh** [comment]
mkvirtualenvで作って`setup.py develop`したところ

```
Traceback (most recent call last):
  File "/home/cocu/workspace/qtile/scripts/../bin/qtile", line 107, in make_qtile
    c = confreader.File(options.configfile, is_restart=options.no_spawn)
  File "/home/cocu/workspace/qtile/bin/libqtile/confreader.py", line 46, in __init__
    from .resources import default_config
  File "/home/cocu/workspace/qtile/bin/libqtile/resources/default_config.py", line 27, in <module>
    from libqtile.config import Key, Screen, Group, Drag, Click
  File "/home/cocu/workspace/qtile/bin/libqtile/config.py", line 29, in <module>
    from . import hook
  File "/home/cocu/workspace/qtile/bin/libqtile/hook.py", line 33, in <module>
    from . import utils
  File "/home/cocu/workspace/qtile/bin/libqtile/utils.py", line 27, in <module>
    from . import xcbq
  File "/home/cocu/workspace/qtile/bin/libqtile/xcbq.py", line 41, in <module>
    from xcffib.xproto import CW, WindowClass, EventMask
ImportError: No module named 'xcffib'
Traceback (most recent call last):
  File "/home/cocu/workspace/qtile/scripts/../bin/qtile", line 130, in <module>
    q = make_qtile()
  File "/home/cocu/workspace/qtile/scripts/../bin/qtile", line 107, in make_qtile
    c = confreader.File(options.configfile, is_restart=options.no_spawn)
  File "/home/cocu/workspace/qtile/bin/libqtile/confreader.py", line 46, in __init__
    from .resources import default_config
  File "/home/cocu/workspace/qtile/bin/libqtile/resources/default_config.py", line 27, in <module>
    from libqtile.config import Key, Screen, Group, Drag, Click
  File "/home/cocu/workspace/qtile/bin/libqtile/config.py", line 29, in <module>
    from . import hook
  File "/home/cocu/workspace/qtile/bin/libqtile/hook.py", line 33, in <module>
    from . import utils
  File "/home/cocu/workspace/qtile/bin/libqtile/utils.py", line 27, in <module>
    from . import xcbq
  File "/home/cocu/workspace/qtile/bin/libqtile/xcbq.py", line 41, in <module>
    from xcffib.xproto import CW, WindowClass, EventMask
ImportError: No module named 'xcffib'
```

**Comment by cocuh** [comment]
なぜかsetup.pyでsetup_requiresに書いてある依存ライブラリが`setup.py develop`で入れてくれなかった様子

このあたりを参考に考察すると良さそう #TODO
https://pythonhosted.org/setuptools/setuptools.html

**Comment by cocuh** [comment]
startup scriptがwaitしているprocessを書き直した

**Comment by cocuh** [comment]
CIが堕ちるけれど、たぶん自分の書いたところではなさそうである。。。
https://travis-ci.org/qtile/qtile/builds/70489773

**Comment by cocuh** [comment]
やれること
- [ ] steamのwindow属性の問題
- [ ] keypress handlerのバグっぽいもの
- [ ] pulseaudioのwidget

**Comment by cocuh** [comment]
Volumeがamixerを指定しているけれど動かない
たぶんparseミスでは

**Comment by cocuh** [comment]
# next task....
- [ ] widget.TaskList()で設定がミスっていてもqtileが堕ちないようにする(default configがrunするようにする)

**Comment by cocuh** [comment]
search a cause of freeze.
- idle
- key press
  でなる

-> loopしてるところよんでlog吐き出すようにする

**Comment by cocuh** [comment]
widget=batteryのコメントアウトで解決するようなので、そこのioが問題っぽい感じで、acpiを叩いても返答が遅いので確信

**Comment by cocuh** [comment]
#TODO
`manager.py` registerWidget内のwidgetMapを見るとdictでkeyがwidget.nameで、`widget/base.py`をみると`self.__class__.__name__.lower()`なので複数の同名widgetを突っ込むと最初に突っ込まれたwidgetのみが有効になりそう

**Comment by cocuh** [comment]
why use widgetMap???

**Comment by cocuh** [comment]
ttps://github.com/qtile/qtile/issues/241

**Comment by cocuh** [comment]
asyncio..
