### ISSUE TITLE
OSS Hack Weekend: KeWata: scipy, pelican: Python : 作業ログ

### ISSUE THREAD

**Issue by KeitaW** [clear-code/sezemi-2015#35]
scipy: https://github.com/scipy/scipy
pelican: https://github.com/getpelican/pelican
作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by KeitaW** [comment]
- 作業（テスト）
- 思っていること（issue投稿のテストをしたいと思っている）
- 備考（brabra）

**Comment by KeitaW** [comment]
- 作業
  git clone後のtest 'nosetests -v sklearn'でエラーが発生．エラー内容

```
Failure: ImportError (dlopen(/Users/keitawatanabe/.pyenv/versions/anaconda-2.0.1/lib/python2.7/site-packages/scipy/sparse/_sparsetools.so, 2): Symbol not found: __ZNSs4_Rep20_S_empty_rep_storageE
  Referenced from: /Users/keitawatanabe/.pyenv/versions/anaconda-2.0.1/lib/python2.7/site-packages/scipy/sparse/_sparsetools.so
  Expected in: dynamic lookup
) ... ERROR

======================================================================
ERROR: Failure: ImportError (dlopen(/Users/keitawatanabe/.pyenv/versions/anaconda-2.0.1/lib/python2.7/site-packages/scipy/sparse/_sparsetools.so, 2): Symbol not found: __ZNSs4_Rep20_S_empty_rep_storageE
  Referenced from: /Users/keitawatanabe/.pyenv/versions/anaconda-2.0.1/lib/python2.7/site-packages/scipy/sparse/_sparsetools.so
  Expected in: dynamic lookup
)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/keitawatanabe/.pyenv/versions/anaconda-2.0.1/lib/python2.7/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/keitawatanabe/.pyenv/versions/anaconda-2.0.1/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/keitawatanabe/.pyenv/versions/anaconda-2.0.1/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/keitawatanabe/Projects/sezemi/scikit-learn/sklearn/__init__.py", line 57, in <module>
    from .base import clone
  File "/Users/keitawatanabe/Projects/sezemi/scikit-learn/sklearn/base.py", line 10, in <module>
    from scipy import sparse
  File "/Users/keitawatanabe/.pyenv/versions/anaconda-2.0.1/lib/python2.7/site-packages/scipy/sparse/__init__.py", line 212, in <module>
    from .csr import *
  File "/Users/keitawatanabe/.pyenv/versions/anaconda-2.0.1/lib/python2.7/site-packages/scipy/sparse/csr.py", line 13, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: dlopen(/Users/keitawatanabe/.pyenv/versions/anaconda-2.0.1/lib/python2.7/site-packages/scipy/sparse/_sparsetools.so, 2): Symbol not found: __ZNSs4_Rep20_S_empty_rep_storageE
  Referenced from: /Users/keitawatanabe/.pyenv/versions/anaconda-2.0.1/lib/python2.7/site-packages/scipy/sparse/_sparsetools.so
  Expected in: dynamic lookup


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```
- おそらくscipy/sparseのバージョンが古い?

**Comment by KeitaW** [comment]
anacondaが問題の原因と思われるので，pyenvで2.7.8を導入してpipからscipyをインストール．同様のテストを行ってみることにする．

**Comment by KeitaW** [comment]
解決

**Comment by KeitaW** [comment]
Editdistance計算アルゴリズムをscipy.spatialに追加してプルリクエストを出してみるという方針に決定．

**Comment by KeitaW** [comment]
現在の懸念点．
- scipy.spatial.distance, sklearn.spatial.distanceのどちらにPRをするか．また，別にライブラリがあるのに考える必要があるのか

**Comment by KeitaW** [comment]
pelica test/test_readers.py line 372 日本語がおかしい．あとで直すこと

**Comment by KeitaW** [comment]
scipyに関しては，scipy devのメーリングリストにscipy.spatial.distance内のメソッドにedit distanceのメソッドを追加するように提案．

**Comment by KeitaW** [comment]
vimでpep8に準拠したコードに自動修正できるように環境を設定．

**Comment by KeitaW** [comment]
autopep8コマンドを用いてpelican/_.py pelican/tests/_.py中のpep8に準拠しない記法を修正

**Comment by KeitaW** [comment]
https://github.com/numpy/numpy/issues/6023 のpython2 と3でのstringの扱いの違い．
