### ISSUE TITLE
OSS Hack Weekend: himaaaatti: qtile Python: 作業ログ

### ISSUE THREAD

**Issue by sux2mfgj** [clear-code/sezemi-2015#40]
https://github.com/qtile/qtile

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by sux2mfgj** [comment]
- 作業：会場に到達した
- 思っていること：新宿の乗り換えが面倒

備考：新宿で乗り換えたつもりが気づいたら西新宿にいた。なにを言っ（

**Comment by sux2mfgj** [comment]
- 作業：インストールを始めた
- 思っていること：cffi周りでコケてる

備考:
~/.xinitrcを以下のように書き換え

```
exec ~/src/qtile/bin/qtile
```

$startx ~/.xinitrc
の結果以下にログを吐くので

$cat ~/.qtile.log

2015-07-11 11:33:40,712 WARNING init_log:93 Starting Qtile
2015-07-11 11:33:40,740 ERROR make_qtile:109 Error while reading config file
Traceback (most recent call last):
  File "/home/hima/src/qtile/bin/qtile", line 107, in make_qtile
    c = confreader.File(options.configfile, is_restart=options.no_spawn)
  File "/home/hima/src/qtile/bin/libqtile/confreader.py", line 46, in **init**
    from .resources import default_config
  File "/home/hima/src/qtile/bin/libqtile/resources/default_config.py", line 27, in <module>
    from libqtile.config import Key, Screen, Group, Drag, Click
  File "/home/hima/src/qtile/bin/libqtile/config.py", line 35, in <module>
    from .widget.base import deprecated
  File "/home/hima/src/qtile/bin/libqtile/widget/**init**.py", line 53, in <module>
    safe_import(".backlight", "Backlight")
  File "/home/hima/src/qtile/bin/libqtile/widget/**init**.py", line 45, in safe_import
    module = importlib.import_module(module_name, package)
  File "/usr/lib/python3.4/importlib/**init**.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/hima/src/qtile/bin/libqtile/widget/backlight.py", line 25, in <module>
    from . import base
  File "/home/hima/src/qtile/bin/libqtile/widget/base.py", line 32, in <module>
    from .. import command, bar, configurable, drawer
  File "/home/hima/src/qtile/bin/libqtile/bar.py", line 24, in <module>
    from . import drawer
  File "/home/hima/src/qtile/bin/libqtile/drawer.py", line 37, in <module>
    from . import pangocffi
  File "/home/hima/src/qtile/bin/libqtile/pangocffi.py", line 59, in <module>
    ffi.include(xcffib.ffi)
  File "/usr/lib/python3.4/site-packages/cffi/api.py", line 430, in include
    type(ffi_to_include).__name__,))
TypeError: ffi.include() expects an argument that is also of type cffi.FFI, not 'CompiledFFI'

**Comment by himaaaatti** [comment]
上記についての備考

```~/.xinitrc
exec ~/src/qtile/bin/qtile
```

**Comment by sux2mfgj** [comment]
- ログ: 上記のエラーが出る原因はxcffib<0.3の時起きないのかもしれない

https://github.com/SimonSapin/cairocffi/issues/58

**Comment by sux2mfgj** [comment]
- ログ: xcffibのバージョンをさげる

$pip install xcffib\=\=0.2.5

別のエラーが発現

$cat ~/.qtile.log

2015-07-11 14:05:15,192 WARNING init_log:93 Starting Qtile
2015-07-11 14:05:15,272 ERROR make_qtile:109 Error while reading config file
Traceback (most recent call last):
  File "/home/hima/src/qtile/bin/qtile", line 107, in make_qtile
    c = confreader.File(options.configfile, is_restart=options.no_spawn)
  File "/home/hima/src/qtile/bin/libqtile/confreader.py", line 46, in **init**
    from .resources import default_config
  File "/home/hima/src/qtile/bin/libqtile/resources/default_config.py", line 27, in <module>
    from libqtile.config import Key, Screen, Group, Drag, Click
  File "/home/hima/src/qtile/bin/libqtile/config.py", line 35, in <module>
    from .widget.base import deprecated
  File "/home/hima/src/qtile/bin/libqtile/widget/**init**.py", line 53, in <module>
    safe_import(".backlight", "Backlight")
  File "/home/hima/src/qtile/bin/libqtile/widget/**init**.py", line 45, in safe_import
    module = importlib.import_module(module_name, package)
  File "/usr/lib/python3.4/importlib/**init**.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/hima/src/qtile/bin/libqtile/widget/backlight.py", line 25, in <module>
    from . import base
  File "/home/hima/src/qtile/bin/libqtile/widget/base.py", line 32, in <module>
    from .. import command, bar, configurable, drawer
  File "/home/hima/src/qtile/bin/libqtile/bar.py", line 24, in <module>
    from . import drawer
  File "/home/hima/src/qtile/bin/libqtile/drawer.py", line 34, in <module>
    import cairocffi
  File "/usr/lib/python3.4/site-packages/cairocffi/__init__.py", line 19, in <module>
    from ._ffi import ffi
  File "/usr/lib/python3.4/site-packages/cairocffi/_ffi.py", line 3, in <module>
    from xcffib._ffi import ffi as _ffi0
  File "/usr/lib/python3.4/site-packages/xcffib/_ffi.py", line 4, in <module>
    ffi = _cffi_backend.FFI('xcffib._ffi',
AttributeError: 'module' object has no attribute 'FFI'

**Comment by sux2mfgj** [comment]
- Log: 昨夜、上記の実行できない現象を解決した

作業内容てきには、昼にやったことと変わらないがメモ
$git clone http://github.com/himaaaatti/qtile
$pip insttall -r requirement.txt
$python setup.py build
$python setup.py develop

**Comment by sux2mfgj** [comment]
- Log: WidgetのGraph.pyに何か追加したいとかんがえた結果bluetoothのruntime_usageを
  /sys/class/bluetoote/<device>/power/runtime_usase
  の内容をグラフに反映するようなもの制作する。

このに作業をこれから入る。

**Comment by sux2mfgj** [comment]
- Log: pull request sended.
  https://github.com/qtile/qtile/pull/695
