### ISSUE TITLE
OSS Hack Weekend: suiyujin: ffaker: Ruby: 作業ログ

### ISSUE THREAD

**Issue by suiyujin** [clear-code/sezemi-2015#41]
https://github.com/ffaker/ffaker

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by suiyujin** [comment]
- 作業：ffaker gemをインストール
- 思っていること：ドキュメントに`gem install ffaker`と書いてあるので、Gemfileに書いて`bundle install`すれば大丈夫だろう

**Comment by suiyujin** [comment]
- 作業：とりあえず日本語のダミーデータをひと通り(JobJA, NameJA)生成してみよう
- 思っていること：複数件生成して確認してみよう

**Comment by suiyujin** [comment]
- 作業：日本語のダミーデータをひと通り生成してみた
- 思っていること：いくつか気になる点がある

プログラム：

``` ruby
require 'ffaker'

class FFakerSample
  class << self

    # JobJA.title
    def run_jobja
      p "JobJA"
      10.times do
        puts FFaker::JobJA.title
      end
    end

    # NameJA
    def run_nameja
      p "NameJA"
      10.times do
        p "-------------"
        puts "first_name: #{FFaker::NameJA.first_name}"
        puts "last_first: #{FFaker::NameJA.last_first}"
        puts "last_name: #{FFaker::NameJA.last_name}"
        puts "name: #{FFaker::NameJA.name}"
      end
    end
  end
end
```

実行結果：

``` shell
[9] pry(main)> FFakerSample.run_jobja
"JobJA"
整体師
航海士
CGデザイナー
競輪選手
麻薬取締役官
プロゴルファー
アクチュアリー
森林インストラクター
モデル
セラピスト
=> 10
[10] pry(main)> FFakerSample.run_nameja
"NameJA"
"-------------"
first_name: 正一
last_first: 仲嶺幸子
last_name: 河村
name: 正治倉内
"-------------"
first_name: 和彦
last_first: 伊波竜也
last_name: 井手
name: 瑛太関口
"-------------"
first_name: 求
last_first: 藤江久
last_name: 武田
name: 光三浦
"-------------"
first_name: 武雄
last_first: 奥優花
last_name: 久保田
name: 汐与那城
"-------------"
first_name: 瞳
last_first: 小橋明美
last_name: 安江
name: 求武田
"-------------"
first_name: 翔平
last_first: 石倉響
last_name: 柘植
name: 真美松野
"-------------"
first_name: 出
last_first: 小園未
last_name: 喜多
name: 早紀大月
"-------------"
first_name: 和彦
last_first: 嘉数忍
last_name: 上田
name: 梓三宅
"-------------"
first_name: 昭一
last_first: 井戸清子
last_name: 広瀬
name: 剛木下
"-------------"
first_name: 心優
last_first: 大江純一
last_name: 川路
name: 栄田岡
=> 10
```

備考：
- nameの順番が#{first_name}#{last_name}で違和感
- name_with_spaceもほしい
  （参考：https://github.com/ffaker/ffaker/commit/335691c16210904951129e66142725abf3c514f4#diff-9144e4d488890fffa372d862fc110957）
- 読みがなやローマ時を対応づけたい
  - 日本語固有の表現だと思うので難しい？
  - 中国語にも読みがなのようなものはあるらしい
- phone_number_ja や address_ja もほしい

メンターの方からの指摘：
実行結果があると良い
（コマンドラインのオプション含めてすべて）
報告する際に報告された方が再現できるように

**Comment by suiyujin** [comment]
- 作業：他の国のjob, name, address, phone_numberなども生成してみる
- 思っていること：参考になるかも

**Comment by suiyujin** [comment]
- 作業：他の国のjob, name, address, phone_numberなども生成してみた
- 思っていること：
  - addressの区分が国ごとに違うのでどう対応するか悩みそう
  - phone_numberのcountry_codeが一定の値しか返してないが、必要なのか
    - fixedなパラメータなのかわかりにくい
  - phone_numberの区切りは半角スペースが多いがハイフンの国もある
  - genderについては中国のものが日本でも使えるが、別に実装する必要はあるか
  - lorem ipsumの日本語版は作れるか

プログラム：

``` ruby
require 'ffaker'

class FFakerSample
  class << self

    # Job
    def run_job
      p "Job"
      10.times do
        puts FFaker::Job.title
      end
    end

    # NameKR
    def run_namekr
      p "NameKR"
      10.times do
        p "-------------"
        puts "first_name: #{FFaker::NameKR.first_name}"
        puts "last_first: #{FFaker::NameKR.last_first}"
        puts "last_name: #{FFaker::NameKR.last_name}"
        puts "name: #{FFaker::NameKR.name}"
        puts "name_with_space: #{FFaker::NameKR.name_with_space}"
      end
    end

    # Address
    def run_address
      p "Address"
      10.times do
        p "-------------"
        puts "building_number: #{FFaker::Address.building_number}"
        puts "city: #{FFaker::Address.city}"
        puts "country: #{FFaker::Address.country}"
        puts "neighborhood: #{FFaker::Address.neighborhood}"
        puts "zip_code: #{FFaker::Address.zip_code}"
      end
    end

  end
end
```

実行結果：

``` shell
[11] pry(main)> FFakerSample.run_job
"Job"
Senior Response Designer
Customer Communications Producer
Regional Intranet Representative
Human Mobility Agent
Lead Tactics Engineer
Principal Creative Analyst
Regional Branding Analyst
District Data Planner
Regional Accountability Agent
National Program Representative
=> 10
[12] pry(main)> FFakerSample.run_namekr
"NameKR"
"-------------"
first_name: 영서
last_first: 형철오
last_name: 묵
name: 계민승
name_with_space: 임 소준
"-------------"
first_name: 제원
last_first: 용연진
last_name: 누
name: 가우종
name_with_space: 애 소민
"-------------"
first_name: 차연
last_first: 룡정현
last_name: 지
name: 뇌동운
name_with_space: 허 일원
"-------------"
first_name: 운오
last_first: 지정재
last_name: 영
name: 맹운태
name_with_space: 복 태길
"-------------"
first_name: 대로
last_first: 계다영
last_name: 고
name: 원창희
name_with_space: 저 은대
"-------------"
first_name: 성준
last_first: 민아영
last_name: 교
name: 온준모
name_with_space: 개 상욱
"-------------"
first_name: 현우
last_first: 곡석운
last_name: 룡
name: 독고천훈
name_with_space: 정 성안
"-------------"
first_name: 유람
last_first: 음동연
last_name: 왕
name: 봉주형
name_with_space: 포 비창
"-------------"
first_name: 범길
last_first: 김세화
last_name: 경
name: 동동윤
name_with_space: 호 정배
"-------------"
first_name: 판겸
last_first: 운형철
last_name: 대
name: 이삼현
name_with_space: 홍 동학
=> 10
[13] pry(main)> FFakerSample.run_address
"Address"
"-------------"
building_number: 49511
city: Madisynside
country: Venezuela, Bolivarian Republic of
neighborhood: Mount Kisco West
[zip_code] is deprecated. For US addresses please use the AddressUS module
zip_code: 26625-5935
"-------------"
building_number: 098
city: Beaulahville
country: Myanmar
neighborhood: East Renton
[zip_code] is deprecated. For US addresses please use the AddressUS module
zip_code: 41841-0466
"-------------"
building_number: 3700
city: North Kennymouth
country: Latvia
neighborhood: Greater Las Vegas National
[zip_code] is deprecated. For US addresses please use the AddressUS module
zip_code: 55031-9616
"-------------"
building_number: 030
city: West Kaleigh
country: Slovenia
neighborhood: Northwest Midlothian/Midlothian Country Club
[zip_code] is deprecated. For US addresses please use the AddressUS module
zip_code: 19130-0177
"-------------"
building_number: 8123
city: East Clintville
country: Moldova, Republic of
neighborhood: Seven Hills Area
[zip_code] is deprecated. For US addresses please use the AddressUS module
zip_code: 50506-7362
"-------------"
building_number: 965
city: New Rosellabury
country: Tajikistan
neighborhood: South of Lake Shore Blvd
[zip_code] is deprecated. For US addresses please use the AddressUS module
zip_code: 83305
"-------------"
building_number: 906
city: Faheychester
country: Kuwait
neighborhood: Allegheny West
[zip_code] is deprecated. For US addresses please use the AddressUS module
zip_code: 96006
"-------------"
building_number: 74114
city: Joanyhaven
country: Côte d'Ivoire
neighborhood: Bushwick South
[zip_code] is deprecated. For US addresses please use the AddressUS module
zip_code: 84881-8848
"-------------"
building_number: 89212
city: North Dameon
country: Austria
neighborhood: Bridesburg
[zip_code] is deprecated. For US addresses please use the AddressUS module
zip_code: 91213
"-------------"
building_number: 128
city: Santaview
country: Costa Rica
neighborhood: Central Chandler
[zip_code] is deprecated. For US addresses please use the AddressUS module
zip_code: 23152-8667
=> 10
```

**Comment by suiyujin** [comment]
- 作業：開発者用にforkしてcloneする
- 思っていること：問題ないはず

**Comment by suiyujin** [comment]
- 作業：テストを実行してみる
- 思っていること：テストの実行の仕方が書いてないかも...？

**Comment by suiyujin** [comment]
- 作業：`rake test`してみる
- 思っていること：`rake -T`すると書いてあったので実行してみる

実行結果：

``` shell
ippe% rake -T                                     [~/sezemi/oss_hack_weekend/fork/ffaker]
rake reference  # Creates REFERENCE.md
rake test       # Run tests
```

**Comment by suiyujin** [comment]
- 作業：テストを実行した
- 思っていること：問題なく実行された

実行結果：

``` shell
ippe% rake test                                   [~/sezemi/oss_hack_weekend/fork/ffaker]
/Users/ippe/.rbenv/versions/2.2.2/bin/ruby -I"lib:test/:lib/"  "/Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/test_address.rb" "test/test_address_au.rb" "test/test_address_br.rb" "test/test_address_ca.rb" "test/test_address_da.rb" "test/test_address_de.rb" "test/test_address_fi.rb" "test/test_address_mx.rb" "test/test_address_nl.rb" "test/test_address_se.rb" "test/test_address_sn.rb" "test/test_address_uk.rb" "test/test_address_us.rb" "test/test_array_utils.rb" "test/test_avatar.rb" "test/test_bacon_ipsum.rb" "test/test_boolean.rb" "test/test_color.rb" "test/test_company.rb" "test/test_company_it.rb" "test/test_company_se.rb" "test/test_conference.rb" "test/test_course_mathematiques.rb" "test/test_course_philosophie.rb" "test/test_dizzle_ipsum.rb" "test/test_education.rb" "test/test_faker.rb" "test/test_food.rb" "test/test_gender.rb" "test/test_gender_cn.rb" "test/test_gender_kr.rb" "test/test_geolocation.rb" "test/test_guid.rb" "test/test_healthcare_ipsum.rb" "test/test_hipster_ipsum.rb" "test/test_html_ipsum.rb" "test/test_identification.rb" "test/test_identification_co.rb" "test/test_identification_es.rb" "test/test_identification_es_cl.rb" "test/test_identification_es_mx.rb" "test/test_identification_kr.rb" "test/test_internet.rb" "test/test_internet_se.rb" "test/test_job.rb" "test/test_job_cn.rb" "test/test_job_fr.rb" "test/test_job_ja.rb" "test/test_job_kr.rb" "test/test_locale.rb" "test/test_lorem.rb" "test/test_lorem_ar.rb" "test/test_lorem_cn.rb" "test/test_lorem_fr.rb" "test/test_lorem_kr.rb" "test/test_module_utils.rb" "test/test_movie.rb" "test/test_name.rb" "test/test_name_br.rb" "test/test_name_cn.rb" "test/test_name_cs.rb" "test/test_name_de.rb" "test/test_name_fr.rb" "test/test_name_ga.rb" "test/test_name_it.rb" "test/test_name_ja.rb" "test/test_name_kr.rb" "test/test_name_mx.rb" "test/test_name_nb.rb" "test/test_name_nl.rb" "test/test_name_ph.rb" "test/test_name_ru.rb" "test/test_name_se.rb" "test/test_name_sn.rb" "test/test_name_th.rb" "test/test_nato_alphabet.rb" "test/test_phone_number.rb" "test/test_phone_number_au.rb" "test/test_phone_number_cu.rb" "test/test_phone_number_de.rb" "test/test_phone_number_kr.rb" "test/test_phone_number_mx.rb" "test/test_phone_number_nl.rb" "test/test_phone_number_se.rb" "test/test_phone_number_sg.rb" "test/test_phone_number_sn.rb" "test/test_skill.rb" "test/test_sports.rb" "test/test_ssn.rb" "test/test_ssn_mx.rb" "test/test_ssn_se.rb" "test/test_string.rb" "test/test_time.rb" "test/test_units.rb" "test/test_units_english.rb" "test/test_units_metric.rb" "test/test_vehicle.rb" "test/test_venue.rb"
Loaded suite /Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader
Started
...............................................................................
...............................................................................
...............................................................................
...............................................................................
...............................................................................
...............................................................................
.....................................................

Finished in 0.309942 seconds.

527 tests, 10798 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

1700.32 tests/s, 34838.78 assertions/s
```

**Comment by suiyujin** [comment]
- 作業：issueとpull requestを読む
- 思っていること：参考にしたい

**Comment by suiyujin** [comment]
- 作業：pull requestをいくつか読んだ
- 思っていること：
  - テストを書けと言われているプルリクがあった
    - 214
    - 160

**Comment by suiyujin** [comment]
---

ここまで午前

**Comment by suiyujin** [comment]
- 作業：テストを読んでみる
- 思っていること：どのようなテストをしているか調べたい

**Comment by suiyujin** [comment]
- 作業：test_name_ja.rbを読んでみた
- 思っていること：
  - test_nameが文字列の長さでしかテストしていないので、正規表現(assert_match)でテストしたい
  - https://github.com/ffaker/ffaker/blob/7edb0375fcb71dfa627598cb63280ff7882fdfc4/test/test_name_ja.rb#L10-12
  - test_first_nameやtest_last_nameなどが無いので、assert_includeでテストしたい

**Comment by suiyujin** [comment]
- 作業：test_name_ja.rbを修正
- 思っていること：
  - test_nameを正規表現でのテストに変更
  - test_first_name, test_last_name, test_last_firstを実装

変更点１(test_nameを正規表現でのテストに変更)：

``` ruby
diff --git a/test/test_name_ja.rb b/test/test_name_ja.rb
index ac69dce..e6107fd 100644
--- a/test/test_name_ja.rb
+++ b/test/test_name_ja.rb
@@ -8,6 +8,7 @@ class TestFakerNameJA < Test::Unit::TestCase
   end

   def test_name
-    assert @tester.name.length >= 2
+    assert_match(/\A(?:\p{Hiragana}|\p{Katakana}|[一-龠々]){2,}\z/, @tester.name)
   end
 end
```

変更点２(test_first_name, test_last_name, test_last_firstを実装)：

``` ruby
diff --git a/test/test_name_ja.rb b/test/test_name_ja.rb
index 5f2be37..6c646b0 100644
--- a/test/test_name_ja.rb
+++ b/test/test_name_ja.rb
@@ -7,7 +7,19 @@ class TestFakerNameJA < Test::Unit::TestCase
     @tester = FFaker::NameJA
   end

+  def test_first_name
+    assert_include(@tester::FIRST_NAMES, @tester.first_name)
+  end
+
+  def test_last_name
+    assert_include(@tester::LAST_NAMES, @tester.last_name)
+  end
+
   def test_name
     assert_match(/\A(?:\p{Hiragana}|\p{Katakana}|[一-龠々]){2,}\z/, @tester.name)
   end
+
+  def test_last_first
+    assert_match(/\A(?:\p{Hiragana}|\p{Katakana}|[一-龠々]){2,}\z/, @tester.last_first)
+  end
 end
```

**Comment by suiyujin** [comment]
- 作業：他言語のnameテストに日本語のnameが通るか調べる
- 思っていること：概要を把握、直すべき点と理由を明確にする

| 種類 | 日本語のnameが通るか |
| --- | --- |
| Name | x |
| NameBR | x |
| NameCN | o |
| NameCS | x |
| NameDE | x |
| NameGa | x |
| NameIT | x |
| NameKR | x |
| NameMX | x |
| NameNB | x |
| NameNL | x |
| NamePH | x |

**Comment by suiyujin** [comment]
- 作業：nameテストの変更理由をまとめなおす
- 思ったこと：
  - 既存のテストでは、ほぼ全ての言語でテストが通ってしまう状況だった
  - 正規表現に修正したことで、中国語以外の言語ではテストが通らなくなる
- まとめ：
  - 既存のテストでは false negative が多発していたのでそれを改善した
- 備考：
  - false positive : 本当は通るべきものがテストを通らない
  - false negative : 本当は通ってはいけないものがテストを通る

**Comment by suiyujin** [comment]
- 作業：nameテストを見直す
- 思ったこと：
  - nameをlast_firstの順に変更するのであれば、その変更をテストするべき
  - last_nameのunion+first_nameのunionでテストしている方が意図が伝わる
  - test_nameでlast_firstのテストをしていれば良い？
  - カスタムアサーションを使って同じテストを使う
    - assert_last_firstを実装する

変更点：

``` ruby
diff --git a/test/test_name_ja.rb b/test/test_name_ja.rb
index 6c646b0..432dd9a 100644
--- a/test/test_name_ja.rb
+++ b/test/test_name_ja.rb
@@ -15,11 +15,18 @@ class TestFakerNameJA < Test::Unit::TestCase
     assert_include(@tester::LAST_NAMES, @tester.last_name)
   end

+  def test_last_first
+    assert_last_first(@tester.last_first)
+  end
+
   def test_name
-    assert_match(/\A(?:\p{Hiragana}|\p{Katakana}|[一-龠々]){2,}\z/, @tester.name)
+    assert_last_first(@tester.name)
   end

-  def test_last_first
-    assert_match(/\A(?:\p{Hiragana}|\p{Katakana}|[一-龠々]){2,}\z/, @tester.last_first)
+  private
+
+  def assert_last_first(actual)
+    last_first_regexp = /(#{@tester::LAST_NAMES.join('|')})(#{@tester::FIRST_NAMES.join('
+    assert_match(last_first_regexp, actual)
   end
 end
```

備考：
- カスタムassert名は短く簡潔に

**Comment by suiyujin** [comment]
- 作業：nameとlast_firstのalias関係を考える
- 思ったこと：
  - name_krではnameメソッドを逆にして、そのaliasとしてlast_firstを定義しているが、last_firstメソッドのaliasとしてnameを定義する方が自然に感じる
  - name_krを参考にしたことは記述する

変更点：

``` ruby
diff --git a/lib/ffaker/name_ja.rb b/lib/ffaker/name_ja.rb
index 4906edb..0325f13 100644
--- a/lib/ffaker/name_ja.rb
+++ b/lib/ffaker/name_ja.rb
@@ -5,10 +5,6 @@ module FFaker
     extend ModuleUtils
     extend self

-    def name
-      "#{first_name}#{last_name}"
-    end
-
     def first_name
       FIRST_NAMES.sample
     end
@@ -20,5 +16,7 @@ module FFaker
     def last_first
       "#{last_name}#{first_name}"
     end
+
+    alias_method :name, :last_first
   end
 end
```

**Comment by suiyujin** [comment]
指摘していただいたこと：
- assert_matchはエラーがわかりにくい
  - power_assertを使うと分かりやすくなる
- サンプル数が多すぎて、unionしてregexpにするのは良くない
  - https://github.com/rr/rr
  - テスト内(setup)でFIRST_NAMESとLAST_NAMESを少ない件数で上書きする など

**Comment by suiyujin** [comment]
---

ここから2日目

**Comment by suiyujin** [comment]
- 作業：assert_last_firstを修正
- 思っていること：どの方針で修正するべきか考えよう

**Comment by suiyujin** [comment]
- 作業：FIRST_NAMESとLAST_NAMESを定義
- 方法：
  - setup内で定数に代入をしてみる

``` ruby
def setup
  @tester = FFaker::NameJA
  @tester::FIRST_NAMES = %w(あきら フミ 三郎)
  @tester::LAST_NAMES = %w(佐藤 高橋 佐々木)
end
```
- テストクラス内でグローバルなモジュールに定数を定義

``` ruby
 class TestFakerNameJA < Test::Unit::TestCase
+  module ::FFaker::NameJA
+    FIRST_NAMES = %w(あきら フミ 三郎)
+    LAST_NAMES = %w(佐藤 高橋 佐々木)
+  end
```
- テストクラス内で先に(startupで)定数を定義

``` ruby
 class TestFakerNameJA < Test::Unit::TestCase
+  def self.startup
+    FFaker::NameJA.const_set(:FIRST_NAMES, %w(あきら フミ 三郎))
+    FFaker::NameJA.const_set(:LAST_NAMES, %w(佐藤 高橋 佐々木))
+  end
```
- テスト用moduleを作成してinclude
- テスト用moduleを作成してprepend
- 結果(setup内で定数に代入をしてみる)：

``` shell
ippe% rake test -v TEST=test/test_name_ja.rb      [~/sezemi/oss_hack_weekend/fork/ffaker]
/Users/ippe/.rbenv/versions/2.2.2/bin/ruby -I"lib:test/:lib/"  "/Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/test_name_ja.rb"
/Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': /Users/ippe/sezemi/oss_hack_weekend/fork/ffaker/test/test_name_ja.rb:8: dynamic constant assignment (SyntaxError)
    @tester::FIRST_NAMES = %w(あきら フミ 三郎)
                          ^
/Users/ippe/sezemi/oss_hack_weekend/fork/ffaker/test/test_name_ja.rb:9: dynamic constant assignment
    @tester::LAST_NAMES = %w(佐藤 高橋 佐々木)
                         ^
        from /Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb:15:in `block in <main>'
        from /Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `select'
        from /Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test/:lib/"  "/Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/test_name_ja.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```

メソッド内で定数の定義はできないためエラーとなった

結果(テストクラス内でグローバルなモジュールに定数を定義)：

``` shell
ippe% rake test -v TEST=test/test_name_ja.rb      [~/sezemi/oss_hack_weekend/fork/ffaker]
/Users/ippe/.rbenv/versions/2.2.2/bin/ruby -I"lib:test/:lib/"  "/Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/test_name_ja.rb"
Loaded suite /Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader
Started
....

Finished in 0.001919 seconds.

4 tests, 4 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

2084.42 tests/s, 2084.42 assertions/s
```

テストは成功しているが、グローバルに定義していると他の部分に影響が起きてしまう恐れがある

結果(テストクラス内で先に(startupで)定数を定義)：

``` shell
ippe% rake test -v TEST=test/test_name_ja.rb      [~/sezemi/oss_hack_weekend/fork/ffaker]
/Users/ippe/.rbenv/versions/2.2.2/bin/ruby -I"lib:test/:lib/"  "/Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/test_name_ja.rb"
Loaded suite /Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader
Started
....

Finished in 0.001771 seconds.

4 tests, 4 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

2258.61 tests/s, 2258.61 assertions/s
```

テストは成功した
先に定義しているのが分かりやすくて良さそう
**shutdownメソッドで定数をremoveしてやる必要がある**
- 結果(テスト用moduleを作成してinclude)：
  include時に定数を定義して、テスト実行後にremoveするというのは分かりにくい
- 結果(テスト用moduleを作成してprepend)：
  Module#prependはruby2.0から追加された機能
  http://www.techscore.com/tech/Ruby/ruby-2.0/prepend/

ffakerはruby1.9から対応しているのでこの機能は使わないほうが良い
（使うのであれば対応バージョンを変更する必要がある）
https://github.com/ffaker/ffaker/blob/master/ffaker.gemspec#L10

備考：
- スコープを指定してincludeやprependする方法もあるらしいので後日調べる

**Comment by suiyujin** [comment]
やるべきこと：
テストの件数による時間を調べる

結果：
- 全件(1078 x 397)のデータの場合

``` shell
ippe% rake test -v TEST=test/test_name_ja.rb      [~/sezemi/oss_hack_weekend/fork/ffaker]
/Users/ippe/.rbenv/versions/2.2.2/bin/ruby -I"lib:test/:lib/"  "/Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/test_name_ja.rb"
Loaded suite /Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader
Started
....

Finished in 0.007594 seconds.

4 tests, 4 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

526.73 tests/s, 526.73 assertions/s
```
- 3 x 3のデータの場合

``` shell
ippe% rake test -v TEST=test/test_name_ja.rb      [~/sezemi/oss_hack_weekend/fork/ffaker]
/Users/ippe/.rbenv/versions/2.2.2/bin/ruby -I"lib:test/:lib/"  "/Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/test_name_ja.rb"
Loaded suite /Users/ippe/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rake/rake_test_loader
Started
....

Finished in 0.001771 seconds.

4 tests, 4 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

2258.61 tests/s, 2258.61 assertions/s
```

定数を全件使ってテストをすると約0.006〜0.007secかかっていたのが
約0.001〜0.002secまで速くなった

**Comment by suiyujin** [comment]
- 作業：test_name_ja.rbのshutdownメソッドで定数をremoveする
- 思ったこと：
  - 定数をremoveしないと他のテストに影響があると考えられるため、removeは必須

変更点：

``` ruby
diff --git a/test/test_name_ja.rb b/test/test_name_ja.rb
index 9c4b766..7088654 100644
--- a/test/test_name_ja.rb
+++ b/test/test_name_ja.rb
@@ -4,9 +4,16 @@ require 'helper'

 class TestFakerNameJA < Test::Unit::TestCase

-  def self.startup
-    FFaker::NameJA.const_set(:FIRST_NAMES, %w(あきら フミ 三郎))
-    FFaker::NameJA.const_set(:LAST_NAMES, %w(佐藤 高橋 佐々木))
+  class << self
+    def startup
+      FFaker::NameJA.const_set(:FIRST_NAMES, %w(あきら フミ 三郎))
+      FFaker::NameJA.const_set(:LAST_NAMES, %w(佐藤 高橋 佐々木))
+    end
+
+    def shutdown
+      FFaker::NameJA.class_eval { remove_const(:FIRST_NAMES) }
+      FFaker::NameJA.class_eval { remove_const(:LAST_NAMES) }
+    end
   end
```
- 備考：
  - startupとshutdownを対応させる
  - 特異メソッドはまとめて記述する

**Comment by suiyujin** [comment]
- 作業：プルリク用にコミットをまとめる
- 思ったこと：
  - コミットメッセージどうしよう
  - 他のプルリクを見てみよう

**Comment by suiyujin** [comment]
- 作業：プルリクを作ってみる
- 思ったこと：
  - 英語難しい
  - まず日本語で作ってみる

**Comment by suiyujin** [comment]
##### プルリクのためのまとめ

どのような動機か：

###### name_ja.rb
- 日本語では#{first_name}#{last_name}の順で記述することはない

###### test_name_ja.rb
- first_name, last_name, last_firstメソッドがテストされていない
- test_nameが文字列のlengthでしかテストしていないので、false nagativeである
  - (どんな文字列でも2文字以上であればテストを通ってしまう)

解決策（変更点を要約）：

###### name_ja.rb
- nameを#{last_name}#{first_name}の順に変更した
  - 韓国語のコミットを参考にした
    - nameの中で逆に実装し、last_firstメソッドをalias化していた
      (https://github.com/ffaker/ffaker/commit/335691c16210904951129e66142725abf3c514f4#diff-9144e4d488890fffa372d862fc110957)
  - last_firstメソッドを残したまま、nameメソッドをalias化した方が自然(natural)なので、そのように変更した

###### test_name_ja.rb
- test_first_name, test_last_name, test_last_firstを追加した
- test_last_firstとtest_nameでは#{last_name}#{first_name}の順になっていることをテストするようにした
  - 全てのデータでassert_matchさせると処理が重たくなってしまうので、テスト用に一時的に定数（small data）を用意するようにした

**Comment by suiyujin** [comment]
作業：英語で書いてみる

メンターの方のアドバイス：
日本語をそのまま訳すのではなく、英語らしい書き方を心がける
- This is a penレベルのシンプルな記述
- 擬人化（This Change do ~）

書いた英語を英和翻訳してみて、分かりにくい英語になってないか調べる

**Comment by suiyujin** [comment]
##### Changes
- FFaker::NameJA.name generate name in the order of last_name, first_name.
- Add test_first_name, test_last_name and test_last_first.
- test_last_first and test_name examine the order of name.

###### FFaker::NameJA.name generate name in the order of last_name, first_name.

Japanese name is not written in order of first_name, last_name like Korean.
I refer to this commit (https://github.com/ffaker/ffaker/commit/335691c16210904951129e66142725abf3c514f4#diff-9144e4d488890fffa372d862fc110957). 
This commit defined last_first as an alias of name.
But I think name should be an alias of last_first, because it is natural.

###### test_last_first and test_name examine the order of name.

https://github.com/suiyujin/ffaker/blob/improve-japanese-name/test%2Ftest_name_ja.rb#L6-16
This section replaces all data to small data, to avoid slowing down.
