### ISSUE TITLE
OSS Hack Weekend: double-y: Django Python: 作業ログ

### ISSUE THREAD

**Issue by yosuke-yasuda** [clear-code/sezemi-2015#45]
https://github.com/django/django

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by yosuke-yasuda** [comment]
- 作業：コントリビュート方法の確認
- 思っていること：github上で行われていないようなので、ちょっと調べることが多そう

**Comment by yosuke-yasuda** [comment]
- 作業：failするテストを見つけた
- 思っていること：テストを数えるメソッドのテストで失敗しているので、そこの実装が怪しい

備考：エラーは以下のとおり

```
./test_runner
+ /Users/yasudayousuke/oss_hack/django_dev/djangodev/bin/python ./runtests.py ./test_runner
Testing against Django installed in '/Users/yasudayousuke/oss_hack/django_dev/django_parent/django'
Creating test database for alias 'default'...
Creating test database for alias 'other'...
.....F...........ss.......................
======================================================================
FAIL: test_duplicates_ignored (test_runner.test_discover_runner.DiscoverRunnerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yasudayousuke/oss_hack/django_dev/django_parent/tests/test_runner/test_discover_runner.py", line 127, in test_duplicates_ignored
    self.assertEqual(single, dups)
AssertionError: 251 != 252
```

歴史が少し古いコミットにいたので、再度テストをまわした
値がすこし変わった

```
OK
Destroying test database for alias 'default'...
Destroying test database for alias 'other'...
+ for dir in '${dirs[@]}'
+ echo ./test_runner
./test_runner
+ /Users/yasudayousuke/oss_hack/django_dev/djangodev/bin/python ./runtests.py ./test_runner
Testing against Django installed in '/Users/yasudayousuke/oss_hack/django_dev/django_parent/django'
Creating test database for alias 'default'...
Creating test database for alias 'other'...
.....F...........ss.......................
======================================================================
FAIL: test_duplicates_ignored (test_runner.test_discover_runner.DiscoverRunnerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yasudayousuke/oss_hack/django_dev/django_parent/tests/test_runner/test_discover_runner.py", line 127, in test_duplicates_ignored
    self.assertEqual(single, dups)
AssertionError: 259 != 260
```

対応イシューはなさそう

**Comment by yosuke-yasuda** [comment]
- 作業：failするテストを見つけた
- 思っていること：ファイルアップロード関連のテストみたい

備考：エラーは以下のとおり

```
OK
Destroying test database for alias 'default'...
Destroying test database for alias 'other'...
+ for dir in '${dirs[@]}'
+ echo ./forms_tests
./forms_tests
+ /Users/yasudayousuke/oss_hack/django_dev/djangodev/bin/python ./runtests.py ./forms_tests
Testing against Django installed in '/Users/yasudayousuke/oss_hack/django_dev/django_parent/django'
Creating test database for alias 'default'...
Creating test database for alias 'other'...
..................................................................................................................F.....................................................................................................................................................................................................................................................................................................................s...........
======================================================================
FAIL: test_imagefield_annotate_with_bitmap_image_after_clean (forms_tests.tests.test_fields.FieldsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yasudayousuke/oss_hack/django_dev/django_parent/tests/forms_tests/tests/test_fields.py", line 862, in test_imagefield_annotate_with_bitmap_image_after_clean
    self.assertIsNone(uploaded_file.content_type)
AssertionError: 'image/bmp' is not None
```

修正は以下のように変更することでできる

```
diff --git a/tests/forms_tests/tests/test_fields.py b/tests/forms_tests/tests/test_fields.py
index bfc88d7..e3b326c 100644
--- a/tests/forms_tests/tests/test_fields.py
+++ b/tests/forms_tests/tests/test_fields.py
@@ -859,7 +859,7 @@ class FieldsTests(SimpleTestCase):
         uploaded_file = f.clean(img_file)

         self.assertEqual('BMP', uploaded_file.image.format)
-        self.assertIsNone(uploaded_file.content_type)
+        self.assertEqual('image/bmp', uploaded_file.content_type)

     # URLField ##################################################################
```

[pillowの変更](https://github.com/python-pillow/Pillow/commit/fe18b039ca9e11c6deed8f21a9e5eca815badbb7)
が原因らしい

**Comment by yosuke-yasuda** [comment]
- 作業：昨日出したプルリクに返信があったので、それに対応
- 思っていること：テストの意図と少しずれていたので、意図に合わせた方法を探す
- 備考：
  MIMEタイプを予測しないケースもあることのテストで、画像でかつMIMEをPillowという依存ライブラリがMIMEを予測しないようなファイルタイプを探す
  tgaというファイル形式が、それにマッチするのでtgaを使うのが良いか
  https://ja.wikipedia.org/wiki/TGA

**Comment by yosuke-yasuda** [comment]
- 作業：テストはパスしたので、プルリクを送る方法を考える（ファイルの追加もあるため）
- 思っていること：似たような変更が過去にあって、それの形式を参考にプルリクを送る
- 備考：
  参考プルリク
  https://github.com/django/django/pull/4869
  送ったプルリク
  https://github.com/django/django/pull/4983

**Comment by yosuke-yasuda** [comment]
- 作業：もう一つ失敗するテストがあるので、調べる
- 思っていること：アサーションのエラーなんで、仕様の変更かな？
- 備考：

```
Testing against Django installed in '/Users/yasudayousuke/oss_hack/django_dev/django_parent/django'
Creating test database for alias 'default'...
Creating test database for alias 'other'...
.....F...........ss.......................
======================================================================
FAIL: test_duplicates_ignored (test_runner.test_discover_runner.DiscoverRunnerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yasudayousuke/oss_hack/django_dev/django_parent/tests/test_runner/test_discover_runner.py", line 127, in test_duplicates_ignored
    self.assertEqual(single, dups)
AssertionError: 259 != 260

----------------------------------------------------------------------
Ran 42 tests in 6.149s

FAILED (failures=1, skipped=2)
Destroying test database for alias 'default'...
Destroying test database for alias 'other'...
```

チケットにした
https://code.djangoproject.com/ticket/25110

**Comment by myokoym** [comment]
実行したコマンドやログ、チケットへのリンクを載せているところや、pull requestの形式をプロジェクトのルールに合わせているところなどがとてもよい進め方だと思いました。おつかれさまでした！
