### ISSUE TITLE
OSS Hack Weekend: tomoasleep: ruby: C, Ruby: 作業ログ

### ISSUE THREAD

**Issue by tomoasleep** [clear-code/sezemi-2015#47]
https://github.com/ruby/ruby

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by tomoasleep** [comment]
- 作業：インストールを始めた
- 思っていること：とりあえず`$HOME/sandbox`的なところにインストールさせる

**Comment by tomoasleep** [comment]
- 作業：ArchLinux環境を用意してrubyをインストールする
- 思っていること：以前に2.1系列をインストールしても`extconf.rb`周りでハングアップしてしまうことがあったのでそれの再現を試してみる

備考: Vagrantboxを https://atlas.hashicorp.com/dreamscapes/boxes/archlinux/versions/2015.07.01 から取ってきてrubyのビルドを試したところ以下のエラーがあった

```
[vagrant@localhost ruby]$ autoconf
[vagrant@localhost ruby]$ ./configure --prefix=$HOME/opt
executable host ruby is required. use --with-baseruby option.; false -C ./tool get-config_files config.guess
executable host ruby is required. use --with-baseruby option.; false -C ./tool get-config_files config.sub
configure: error: cannot run /bin/sh tool/config.sub
```

rubyをインストールするのにはrubyが必要っぽい

**Comment by tomoasleep** [comment]
- 作業: 並行してMacbookにrubyのtrunkを落としてきてbuildしている
- 備考: `make`まで出来たが、`make check`を走らせてみると失敗する

```
        CC = clang
        LD = ld
        LDSHARED = clang -dynamic -bundle
        CFLAGS = -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Werror=pointer-arith -Werror=write-strings -Werror=declaration-after-statement -Werror=shorten-64-to-32 -Werror=implicit-function-declaration -Werror=division-by-zero -Werror=deprecated-declarations -Werror=extra-tokens   -pipe
        XCFLAGS = -D_FORTIFY_SOURCE=2 -fstack-protector -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT -fPIE
        CPPFLAGS = -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I. -I.ext/include/x86_64-darwin14 -I./include -I.
        DLDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -fstack-protector -Wl,-u,_objc_msgSend -Wl,-pie -framework CoreFoundation
        SOLIBS = -lgmp
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix
generating enc.mk
generating encdb.h
encdb.h unchanged
making enc
make[1]: Nothing to be done for `enc'.
making srcs under enc
make[1]: Nothing to be done for `srcs'.
generating transdb.h
transdb.h unchanged
making trans
make[1]: Nothing to be done for `./enc/trans'.
making encs
generating makefile exts.mk
Failed to configure openssl. It will not be installed.
configuring rbconfig/sizeof
configuring ripper
configuring socket
make[2]: Nothing to be done for `all'.
installing default bigdecimal libraries
installing default date_core libraries
installing digest libraries
installing default digest libraries
installing default sha2 libraries
installing default fiddle libraries
installing default console libraries
installing default libraries
installing default nkf libraries
make[2]: Nothing to be done for `all'.
installing default pathname libraries
installing default psych libraries
installing default pty libraries
linking shared-object rbconfig/sizeof.bundle
linking shared-object ripper.bundle
installing default ripper libraries
checking ../.././parse.y and ../.././ext/ripper/eventids2.c
linking shared-object socket.bundle
installing default socket libraries
installing default syslog libraries
installing tcltklib libraries
installing default tcltklib libraries
        CC = clang
        LD = ld
        LDSHARED = clang -dynamic -bundle
        CFLAGS = -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Werror=pointer-arith -Werror=write-strings -Werror=declaration-after-statement -Werror=shorten-64-to-32 -Werror=implicit-function-declaration -Werror=division-by-zero -Werror=deprecated-declarations -Werror=extra-tokens   -pipe
        XCFLAGS = -D_FORTIFY_SOURCE=2 -fstack-protector -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT -fPIE
        CPPFLAGS = -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I. -I.ext/include/x86_64-darwin14 -I./include -I.
        DLDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -fstack-protector -Wl,-u,_objc_msgSend -Wl,-pie -framework CoreFoundation
        SOLIBS = -lgmp
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix
make[2]: `ruby' is up to date.
Generating RDoc documentation

No newer files.

  Files:      0

  Classes:    0 (0 undocumented)
  Modules:    0 (0 undocumented)
  Constants:  0 (0 undocumented)
  Attributes: 0 (0 undocumented)
  Methods:    0 (0 undocumented)

  Total:      0 (0 undocumented)
    0.00% documented

  Elapsed: 0.0s


test succeeded
PASS all 1010 tests
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems "./bootstraptest/runner.rb" --ruby="ruby --disable-gems"   ./KNOWNBUGS.rb
2015-07-11 11:06:11 +0900
Driver is ruby 2.3.0dev (2015-07-11 trunk 51215) [x86_64-darwin14]
Target is ruby 2.3.0dev (2015-07-11 trunk 51215) [x86_64-darwin14]

KNOWNBUGS.rb  PASS 0
No tests, no problem
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems "./test/runner.rb" --ruby="./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems" --excludes=./test/excludes
/Users/tomoya/Projects/ruby/test/rubygems/test_bundled_ca.rb: cannot load such file -- openssl
Skipping `gem cert` tests.  openssl not found.
/Users/tomoya/Projects/ruby/lib/rubygems/test_case.rb:1395:in `load_cert': uninitialized constant Gem::TestCase::OpenSSL (NameError)
        from /Users/tomoya/Projects/ruby/test/rubygems/test_gem_request.rb:9:in `<class:TestGemRequest>'
        from /Users/tomoya/Projects/ruby/test/rubygems/test_gem_request.rb:6:in `<top (required)>'
        from /Users/tomoya/Projects/ruby/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/tomoya/Projects/ruby/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/tomoya/Projects/ruby/test/lib/test/unit.rb:812:in `block in non_options'
        from /Users/tomoya/Projects/ruby/test/lib/test/unit.rb:806:in `each'
        from /Users/tomoya/Projects/ruby/test/lib/test/unit.rb:806:in `non_options'
        from /Users/tomoya/Projects/ruby/test/lib/test/unit.rb:63:in `process_args'
        from /Users/tomoya/Projects/ruby/test/lib/test/unit.rb:101:in `process_args'
        from /Users/tomoya/Projects/ruby/test/lib/test/unit.rb:951:in `process_args'
        from /Users/tomoya/Projects/ruby/test/lib/test/unit.rb:956:in `run'
        from /Users/tomoya/Projects/ruby/test/lib/test/unit.rb:963:in `run'
        from ./test/runner.rb:45:in `<main>'
make: *** [yes-test-all] Error 1
```

**Comment by tomoasleep** [comment]
- 作業: `make check`を走らせてみると失敗する件をRedmineで報告がされてないか検索する。
- 思っていること：`README`を読んで実行する内容で、環境非依存な感じがするので既に報告されているのではないかと考えてとりあえず検索した。

備考： 
2.3-devのbugに関して検索してみたが、関係有るものは見当たらなかった。
`openssl`, `make check`でも検索しているがヒットする件数が多すぎて目を通すのがつらい。。。、
絞り込みをもっとした方がいいかもしれない。

**Comment by tomoasleep** [comment]
- 作業： インストールとアンインストールを試してみた。
- 思っていること：とりあえずインストールアンインストールが正常に動くかチェックしたい。

備考：
`./configure --prefix=$HOME/sandbox && make && make install`して`make uninstall`してみた。

問題(?)があって、make uninstallで$HOMEを消そうとしてしまう？

## 出力

```
$ make uninstall                                                                                                                                                                                        
Permission denied @ dir_s_rmdir - /Users/tomoya
make: *** [uninstall] Error 1
```

```
$ make uninstall -n
echo > /dev/null
./miniruby -I./lib -I. -I.ext/common  ./tool/rbuninstall.rb --destdir= .installed.list
```

[./tool/rbuninstall.rb](https://github.com/ruby/ruby/blob/trunk/tool/rbuninstall.rb)は出力を制御して削除しているのでログが消されてしまうようになっているが、`.installed.list`内のものを消しているみたいなので、それに不穏なファイルが含まれていないか後でチェックする。

**Comment by tomoasleep** [comment]
[./tool/rbuninstall.rb](https://github.com/ruby/ruby/blob/trunk/tool/rbuninstall.rb)は親ディレクトリに対して`rmdir`を行うようになっているらしい

**Comment by tomoasleep** [comment]
作業：`make check`でチェックを行う

`make check`で失敗するが、それはextのopensslがビルド失敗しているのが原因らしく、

https://github.com/ruby/ruby/blob/c8b3f1b470e343e7408ab5883f046b1056d94ccc/ext/openssl/extconf.rb#L62 の通り、Appleの標準のOpenSSLは使わない様にしているからだった。

http://stackoverflow.com/questions/17181075/openssl-error-installing-ruby-2-0-0-p195-on-mac-with-rbenv
https://redmine.ruby-lang.org/issues/10099
https://redmine.ruby-lang.org/issues/5853

とか、似たような箇所で引っかかっていることが多いのと、
このことが失敗するまで気づかないのでREADMEとかに注意書きを追加したほうが良い気がする。

**Comment by tomoasleep** [comment]
作業: make check で失敗

```
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems "./test/runner.rb" --ruby="./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems" --excludes=./test/excludes
Run options: "--ruby=./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems" --excludes=./test/excludes

# Running tests:

[10045/15705] TestProcess#test_deadlock_by_signal_at_forking = 61.01 s
  1) Failure:
TestProcess#test_deadlock_by_signal_at_forking [/Users/tomoya/Projects/ruby/test/ruby/test_process.rb:2020]:
assert_separately failed
pid 91942 killed by SIGKILL (signal 9)

Finished tests in 607.633912s, 25.8363 tests/s, 3668.9838 assertions/s.
15699 tests, 2229399 assertions, 1 failures, 0 errors, 37 skips

ruby -v: ruby 2.3.0dev (2015-07-11 trunk 51215) [x86_64-darwin14]
make: *** [yes-test-all] Error 1
```

**Comment by tomoasleep** [comment]
作業: Macのopensslだと`ext/openssl`のビルドが出来ない点について分かりやすくさせることを提案するのを考えている。

考えている点は、「どう、分かりやすくすべき、と話の方向性を持たせるか」、「どこに明記もらったほうがいいか」、「どこに報告するか」という点。

## どう、分かりやすくすべき、と話の方向性を持たせるか

現状、ビルドするまでで気づかない(`./configure`ではチェックされておらず、`make install`するまで気づかずエラーメッセージも埋もれやすい)のと、そのために似たような報告が相次いでいる。↓

http://stackoverflow.com/questions/17181075/openssl-error-installing-ruby-2-0-0-p195-on-mac-with-rbenv
https://redmine.ruby-lang.org/issues/10099
https://redmine.ruby-lang.org/issues/5853

という感じで書こうと思っている

## どこに明記してもらうのがいいか

個人的には [README](https://github.com/ruby/ruby/blob/trunk/README.md) が目につきやすいのと、ビルド方法が載っているので良いと思っている。

## どこに報告するか

https://redmine.ruby-lang.org/projects/ruby-trunk なんだろうけど、トラッカーの種類に悩んでいる。
`misc`が適当？

**Comment by tomoasleep** [comment]
# 報告の日本語版草稿

標準添付のopensslをMacOSXでビルドすると、AppleがバンドルしているOpenSSLだと以下の様なエラーメッセージが出て標準添付のopensslのビルドに失敗してスキップされてしまうのですが、`configure && make`してビルドすると長いメッセージに埋もれてしまい、このことに気づきにくいと感じました。(私はopensslが必要なコードを使って初めてスキップされたことに気づきました。)

```
configuring openssl
Ignore OpenSSL broken by Apple.
Please use another openssl. (e.g. using `configure --with-openssl-dir=/path/to/openssl')
Failed to configure openssl. It will not be installed.
```

(エラーメッセージが出るのは、[ここのソースコード](https://github.com/ruby/ruby/blob/e7d6fc01dd72e43cd0ff7c20c3da9f20483822f3/ext/openssl/extconf.rb#L62)の処理によるようです。)

Macでビルドする際には`configure --with-openssl-dir=/path/to/openssl'`と他のOpenSSLの場所を指定するようにREADME等に明記したほうが良いと思うのですが、いかがでしょうか。

どこの箇所に説明を追加するべきかを教えていただければ、以下の内容を書き足してプルリクエストを送ります:-)

``````
You cannot use openssl provided by Apple to build standard library openssl.
If you use OSX, you should install another openssl and run ```./configure --with-openssl-dir=/path/to/another-openssl```.
For Homebrew user, run 'brew install openssl' and then ```./configure --with-openssl-dir=`brew prefix openssl` ```.
``````

AppleのOpenSSLを使用してしまっているせいで標準添付のOpenSSLのビルドに失敗している方が他にもいるようです。
- http://stackoverflow.com/questions/17181075/openssl-error-installing-ruby-2-0-0-p195-on-mac-with-rbenv
- https://redmine.ruby-lang.org/issues/5853

**Comment by tomoasleep** [comment]
# Failed to build standard library openssl on OSX 10.10.4 (Draft of report to ruby-trunk)

I failed to build standard library openssl when I use OpenSSL provided by Apple.
When I tried to build ruby by running `./configure && make`,
building of standard library openssl failed and was skipped.
I couldn't find the following error message because other long messages hid the message.
I noticed that I failed to build standard library openssl when I used a code which requires standard library openssl.

```
configuring openssl
Ignore OpenSSL broken by Apple.
Please use another openssl. (e.g. using `./configure --with-openssl-dir=/path/to/openssl')
Failed to configure openssl. It will not be installed.
```

([This code](https://github.com/ruby/ruby/blob/e7d6fc01dd72e43cd0ff7c20c3da9f20483822f3/ext/openssl/extconf.rb#L62) would raise this error.)

I think that it is hard to find this message and documents should describe that OSX users should specify another openssl library as  `--with-openssl-dir` parameter of the configure script.
What do you think?

If you tell me a proper place to add the description, I will add such description and send a pull request :-)

``````
You cannot use openssl provided by Apple to build standard library openssl.
If you use OSX, you should install another openssl and run ```./configure --with-openssl-dir=/path/to/another-openssl```.
For Homebrew user, run 'brew install openssl' and then ```./configure --with-openssl-dir=`brew prefix openssl` ```.
``````

There are other people failing to build standard library openssl because of using Apple OpenSSL.
- https://redmine.ruby-lang.org/issues/5853
- https://www.ruby-forum.com/topic/4411415
- http://stackoverflow.com/questions/17181075/openssl-error-installing-ruby-2-0-0-p195-on-mac-with-rbenv
- http://spring-mt.tumblr.com/post/35775477040/openssl-ruby-2-0-0-preview1-bundle (Japanese)

---

In Japanese, (日本語訳)

**Comment by tomoasleep** [comment]
https://github.com/clear-code/sezemi-2015/issues/47#issuecomment-120593508
- https://redmine.ruby-lang.org/issues/10099

はよく見るとちょっと違うので書かなくても良さそう

**Comment by tomoasleep** [comment]
https://github.com/clear-code/sezemi-2015/issues/47#issuecomment-120593508 を最終確認してもらってOKもらったのでトラッキングシステムに送ってみようと思います〜

**Comment by tomoasleep** [comment]
https://redmine.ruby-lang.org/issues/11345 報告した

**Comment by tomoasleep** [comment]
作業: 出来るようなイシューがあるかを探す
思っていること: なにか出来そうなこと+面白い内容があるかもしれない

備考: https://redmine.ruby-lang.org/projects/ruby-trunk/issues のBugをあれこれ読んでみて、解決出来そうな物を探す。

## 現時点で読んだバグ報告一覧
- https://bugs.ruby-lang.org/issues/11186 : thunkで試したが再現しなかった(過去のverでは再現したので修正された？)
- https://bugs.ruby-lang.org/issues/11160 : thunkで再現した(ドキュメントを読んで仕様に反しているのか見てみる)

**Comment by tomoasleep** [comment]
https://github.com/clear-code/sezemi-2015/issues/47#issuecomment-120687342 
https://bugs.ruby-lang.org/issues/11160 から`Proc#call`の実装を読んでみたが、
`Proc#call`の実装は意味に`Proc.new`を呼んでいて、ブロック引数からProcオブジェクトを得てそれを渡しているようなので、Procのサブクラスのインスタンスを引数に渡しても、パラメータはProcのインスタンスになってしまう。

…混乱しやすいので整理すると、

```
def test
  class ProcPlus < Proc; end
  callee = Proc.new { |&x| p x.class }
  procplus = ProcPlus.new {}
  callee.call(&procplus)
end
# The return value of this method isn't 'ProcPlus' but 'Proc'
```

このメソッドの返り値が'Proc'になってしまうのは、`callee.call(&procplus)`した際に`Proc#call`が呼ばれるが、このメソッドは内部で`Proc.new`と同等のコードを実行していて。これは`Proc.new &procplus`と同等なので`callee`のパラメータ`x`はProcクラスのインスタンスになってしまう。

## 直すべき？

直すべきだと思う。
[るりまのブロック引数についてのマニュアル](http://docs.ruby-lang.org/ja/2.2.0/doc/spec=2fcall.html#block)は、ブロック引数には`to_proc`を持つメソッドであることのみを要求していて、`ProcPlus#to_proc`は`ProcPlus`のインスタンスを返すので現在の仕様と合っていないのでは？？

困る話として、ブロック引数が不意にProcに変換されてしまうので、Procのラッパークラス、サブクラスを作ってみてもProcになってしまってバグるということが起こりそう。
(もうちょい困る例として現実的なコードを作って見たほうが良さそう)

## ついでに

これ挙動おかしくない？？

```
(ρ _-)ノ ~/sandbox/bin/irb
irb(main):001:0> class ProcPlus < Proc
irb(main):002:1> def to_proc
irb(main):003:2> Proc.new {2}
irb(main):004:2> end
irb(main):005:1> end
=> :to_proc
irb(main):006:0>  callee = Proc.new { |&blk| blk.call }
=> #<Proc:0x007f9ce19050d0@(irb):6>
irb(main):007:0> procplus = ProcPlus.new { 1 }
=> #<ProcPlus:0x007f9ce3019fc8@(irb):7>
irb(main):008:0>  callee.call(&procplus)
=> 1
irb(main):009:0> procplus.to_proc
=> #<Proc:0x007f9ce30097e0@(irb):3>
irb(main):010:0> procplus.to_proc.call
=> 2
irb(main):011:0>
```

**Comment by tomoasleep** [comment]
https://github.com/clear-code/sezemi-2015/issues/47#issuecomment-120689971 の件については
今自分がこれで困っているということがないので、ユースケースがないので「こういう実装がいいと思います」というと形でパッチを送るしか無いねいう話をしました
