### ISSUE TITLE
OSS Hack Weekend: Henoc: scala-csv: Scala: 作業ログ

### ISSUE THREAD

**Issue by henoc** [clear-code/sezemi-2015#51]
https://github.com/tototoshi/scala-csv

作業ログは、参加者が、このイベントを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- 参加者は作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- 参加者が困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
- 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````

**Comment by henoc** [comment]
- 作業 : インストール
- 思っていること : mavenで使ったことはあるがsbtで使ったことはないので詰まりそう

**Comment by henoc** [comment]
- 作業  
  ライブラリを試す  
  自前のcsvファイルでパースに失敗する  
  エスケープ文字に対応していない模様(csvの方言の1つらしい)  
- 思考  
  csvの各種方言に対応したパーサーを作ってもいいかも???  

```
Exception in thread "main" com.github.tototoshi.csv.MalformedCSVException: "36016","I\"s","I\"s"

    at com.github.tototoshi.csv.CSVParser$.parse(CSVParser.scala:221)
    at com.github.tototoshi.csv.CSVParser.parseLine(CSVParser.scala:291)
    at com.github.tototoshi.csv.CSVReader.parseNext$1(CSVReader.scala:45)
    at com.github.tototoshi.csv.CSVReader.readNext(CSVReader.scala:54)
    at com.github.tototoshi.csv.CSVReader$$anonfun$toStream$1.apply(CSVReader.scala:91)
    at com.github.tototoshi.csv.CSVReader$$anonfun$toStream$1.apply(CSVReader.scala:91)
    at scala.collection.immutable.Stream$.continually(Stream.scala:1279)
    at scala.collection.immutable.Stream$$anonfun$continually$1.apply(Stream.scala:1279)
    at scala.collection.immutable.Stream$$anonfun$continually$1.apply(Stream.scala:1279)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223)
    at scala.collection.immutable.Stream$$anonfun$takeWhile$1.apply(Stream.scala:941)
    at scala.collection.immutable.Stream$$anonfun$takeWhile$1.apply(Stream.scala:941)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223)
    at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
    at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233)
    at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223)
    at scala.collection.generic.Growable$class.loop$1(Growable.scala:54)
    at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:57)
    at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183)
    at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:45)
    at scala.collection.TraversableLike$class.to(TraversableLike.scala:635)
    at scala.collection.AbstractTraversable.to(Traversable.scala:104)
    at scala.collection.TraversableOnce$class.toList(TraversableOnce.scala:292)
    at scala.collection.AbstractTraversable.toList(Traversable.scala:104)
    at com.github.tototoshi.csv.CSVReader.all(CSVReader.scala:94)
    at Main$.main(Main.scala:16)
    at Main.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by mumoshu** [comment]
> 思っていること : mavenで使ったことはあるがsbtで使ったことはないので詰まりそう

sbtを使うところで何か詰まったことがあれば、後で振り返るために作業ログに追記しておくとよいかもしれませんね :+1:

**Comment by mumoshu** [comment]
> テストを実行
> ↑のときもログを残す
> https://github.com/clear-code/sezemi-2015/blob/master/oss-hack-weekend/scenario1.md#1030-開発

動かすところまで終わっていたら、↑の通りテストも実行してみるとよいですね :+1:

**Comment by mumoshu** [comment]
(他の方への参考) scala-csvのGitHubレポジトリはここですね https://github.com/tototoshi/scala-csv

**Comment by henoc** [comment]
なるほど〜〜，とりあえずsbtでは詰まりませんでした!
- 作業
  scala-cvsの開発用をgit cloneして，intelliJでtestを実行するがエラーが出る(シェルではうまくいく)
  An exception or error caused a run to abort. This may have been caused by a problematic custom reporter.
  java.lang.NoClassDefFoundError: scala/xml/MetaData
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2581)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
  at org.scalatest.tools.Runner$.run(Runner.scala:883)
  at org.scalatest.tools.Runner.run(Runner.scala)
  at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
  at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
  Caused by: java.lang.ClassNotFoundException: scala.xml.MetaData
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 14 more
- 思考
  困った

**Comment by henoc** [comment]
- 作業  
  依存していたscalatestのバージョンを最新(2.2.4)にしたらエラーが消えた  
  intelliJから古いscalatestを使ったときに起こるエラーのよう，がよくわからない…  
- 思考
  scala-cvsの提供するメソッドの使い方などを確認していきたい

**Comment by henoc** [comment]
- 作業
  とりあえずscalatestのバージョンを2.2.4にしてプルリクした

**Comment by mumoshu** [comment]
(共有) 2日目はgitbucketに取り組まれてるのですね :+1:

https://github.com/clear-code/sezemi-2015/issues/71

**Comment by kou** [comment]
お疲れ様でした！
